#!/usr/bin/env bash

set -euo pipefail

if [[ ${BUILDKITE_COMMAND_EXIT_STATUS:-0} != '0' ]]; then
  echo '--- Skipping S3 sync because the command failed'
  exit 0
fi

PACKAGE_JSON="${BUILDKITE_PLUGIN_AWS_S3_SYNC_PACKAGE_JSON:-package.json}"

if [[ -f ${PACKAGE_JSON} ]] ; then
    VERSION="$(jq '.version' "${PACKAGE_JSON}" | sed "s/\"//g")"
else 
    echo "package.json does not exist at the specified path, exiting.."
    exit 1
fi

args=()

# By default delete files from destination that don't exist in source 
args+=("--delete")

# TODO support more ACLs
if [[ "${BUILDKITE_PLUGIN_AWS_S3_SYNC_ACL}" == "public-read" ]] ; then
  args+=("--acl" "${BUILDKITE_PLUGIN_AWS_S3_SYNC_ACL}")
fi

# Set object cache control to string provided
if [[ -n "${BUILDKITE_PLUGIN_AWS_S3_SYNC_CACHE_CONTROL:-}" ]] ; then
  args+=("--cache-control" "${BUILDKITE_PLUGIN_AWS_S3_SYNC_CACHE_CONTROL}")
fi

echo -ne 'Running: aws s3 sync ' >&2
# Print all the arguments, with a space after, properly shell quoted
printf "%q " "${args[@]}"
echo

# Sync version number
echo "--- :s3: Syncing ${BUILDKITE_PLUGIN_AWS_S3_SYNC_SOURCE} to ${BUILDKITE_PLUGIN_AWS_S3_SYNC_DESTINATION}/${VERSION}"
aws s3 sync "${BUILDKITE_PLUGIN_AWS_S3_SYNC_SOURCE}" "${BUILDKITE_PLUGIN_AWS_S3_SYNC_DESTINATION}/${VERSION}" "${args[@]}"

# Sync latest
echo "--- :s3: Syncing ${BUILDKITE_PLUGIN_AWS_S3_SYNC_SOURCE} to ${BUILDKITE_PLUGIN_AWS_S3_SYNC_DESTINATION}/latest"
aws s3 sync "${BUILDKITE_PLUGIN_AWS_S3_SYNC_SOURCE}" "${BUILDKITE_PLUGIN_AWS_S3_SYNC_DESTINATION}/latest" "${args[@]}"
